# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-13 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0011_add_email_basket_attribute_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketChallanVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('voucher_number', models.CharField(max_length=32, unique=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('due_date', models.DateTimeField()),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket.Basket', verbose_name='Basket')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
    ]
