# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-27 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0036_coupon_notify_email_attribute'),
        ('basket', '0012_basketchallanvoucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketchallanvoucher',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Product', verbose_name='Product'),
        ),
    ]
